import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {
  useQuery,
  QueryClient,
  QueryClientProvider,
} from "@tanstack/react-query";
import { TransportProvider } from "@bufbuild/connect-query";
import { createConnectTransport } from "@bufbuild/connect-web";
import { getPet } from "../gen/js/proto/pet/v1/pet-PetStoreService_connectquery";

const inter = Inter({ subsets: ["latin"] });

const queryClient = new QueryClient();

export default function Home() {
  const transport = createConnectTransport({
    baseUrl: "/api",
  });

  return (
    <TransportProvider transport={transport}>
      <QueryClientProvider client={queryClient}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <div className={styles.center}>
            <div className={inter.className}>
              <Content />
            </div>
          </div>
        </main>
      </QueryClientProvider>
    </TransportProvider>
  );
}

function Content() {
  const { isLoading, isError, data } = useQuery(
    getPet.useQuery({ petId: "123" })
  );
  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (isError) {
    return <div>Error</div>;
  }

  return (
    <div>
      <div>{data.pet?.name}</div>
      <div>{data.pet?.createdAt?.toDate()?.toLocaleDateString()}</div>
    </div>
  );
}